# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 788)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.informationGrid = QtWidgets.QGridLayout()
        self.informationGrid.setObjectName("informationGrid")
        self.welcome = QtWidgets.QLabel(self.centralwidget)
        self.welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome.setObjectName("welcome")
        self.informationGrid.addWidget(self.welcome, 0, 0, 1, 3)
        self.refreshBlogButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshBlogButton.setObjectName("refreshBlogButton")
        self.informationGrid.addWidget(self.refreshBlogButton, 3, 0, 1, 1)
        self.detailButton = QtWidgets.QPushButton(self.centralwidget)
        self.detailButton.setObjectName("detailButton")
        self.informationGrid.addWidget(self.detailButton, 3, 2, 1, 1)
        self.blogTable = QtWidgets.QTableView(self.centralwidget)
        self.blogTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.blogTable.setObjectName("blogTable")
        self.informationGrid.addWidget(self.blogTable, 1, 0, 1, 3)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setObjectName("clearButton")
        self.informationGrid.addWidget(self.clearButton, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.informationGrid, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.featuresGrid = QtWidgets.QGridLayout()
        self.featuresGrid.setObjectName("featuresGrid")
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setObjectName("updateButton")
        self.featuresGrid.addWidget(self.updateButton, 0, 0, 1, 1)
        self.keywordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.keywordEdit.setObjectName("keywordEdit")
        self.featuresGrid.addWidget(self.keywordEdit, 1, 2, 1, 1)
        self.keywordButton = QtWidgets.QPushButton(self.centralwidget)
        self.keywordButton.setObjectName("keywordButton")
        self.featuresGrid.addWidget(self.keywordButton, 1, 0, 1, 1)
        self.updateEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.updateEdit.setObjectName("updateEdit")
        self.featuresGrid.addWidget(self.updateEdit, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.featuresGrid, 3, 0, 1, 3)
        self.refreshServerButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshServerButton.setObjectName("refreshServerButton")
        self.gridLayout.addWidget(self.refreshServerButton, 2, 0, 1, 1)
        self.subscribeButton = QtWidgets.QPushButton(self.centralwidget)
        self.subscribeButton.setObjectName("subscribeButton")
        self.gridLayout.addWidget(self.subscribeButton, 2, 1, 1, 1)
        self.unsubscribeButton = QtWidgets.QPushButton(self.centralwidget)
        self.unsubscribeButton.setObjectName("unsubscribeButton")
        self.gridLayout.addWidget(self.unsubscribeButton, 2, 2, 1, 1)
        self.serverTable = QtWidgets.QTableView(self.centralwidget)
        self.serverTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.serverTable.setObjectName("serverTable")
        self.gridLayout.addWidget(self.serverTable, 1, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welcome.setText(_translate("MainWindow", "推荐列表"))
        self.refreshBlogButton.setText(_translate("MainWindow", "刷新"))
        self.detailButton.setText(_translate("MainWindow", "详细 ..."))
        self.clearButton.setText(_translate("MainWindow", "清除所有"))
        self.label.setText(_translate("MainWindow", "服务器列表"))
        self.updateButton.setText(_translate("MainWindow", "更新话题"))
        self.keywordEdit.setText(_translate("MainWindow", "蛋白"))
        self.keywordButton.setText(_translate("MainWindow", "关键词查询"))
        self.updateEdit.setText(_translate("MainWindow", "大美北大"))
        self.refreshServerButton.setText(_translate("MainWindow", "刷新服务器"))
        self.subscribeButton.setText(_translate("MainWindow", "订阅 ..."))
        self.unsubscribeButton.setText(_translate("MainWindow", "退订"))

